module.exports = {
  mode: 'jit',
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'media', // or 'media' or 'class'
  theme: {
    extend: {
      animation: {
        'bounce-x': 'bounceX 1s infinite',
      },
      colors: {
        'accent-1': '#333',
        'primary-main': '#7D2BD0',
        'primary-surface': '#FAF5FF',
        'primary-border': '#DFCEEF',
        'primary-hover': '#6D28A8',
        'primary-pressed': '#3E1568',
        'primary-focus': '#E5D5F6',
        'neutral-100': '#FAFAFA',
        'neutral-200': '#F5F5F5',
        'neutral-300': '#EDEDED',
        'neutral-400': '#E0E0E0',
        'neutral-500': '#C2C2C2',
        'neutral-600': '#9E9E9E',
        'neutral-700': '#757575',
        'neutral-800': '#616161',
        'neutral-900': '#404040',
        'neutral-1000': '#0A0A0A',
        'danger-main': '#CB3A31',
        'danger-surface': '#FFF5F5',
        'danger-border': '#EEBDBA',
        'danger-hover': '#B0352E',
        'danger-pressed': '#7D241',
        'warning-main': '#DA9A1B',
        'warning-surface': '#FFFAF0',
        'warning-border': '#FFE5B2',
        'warning-hover': '#BD8A26',
        'warning-pressed': '#8C671C',
        'success-main': '#43936C',
        'success-surface': '#F7F7F7',
        'success-border': '#B8DBCA',
        'success-hover': '#387A5A',
        'success-pressed': '#20573D',
        'info-main': '#3267E3',
        'info-surface': '#F0F3FF',
        'info-border': '#B1C5F6',
        'info-hover': '#114CD6',
        'info-pressed': '#11317D',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography'), require('@tailwindcss/aspect-ratio')],
}
