import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
	return (
		<div className="p-4">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="p-5 bg-red">
				<div className="bg-[linear-gradient(208.89deg,_#7D2BD0_-170.41%,_#000000_92.37%)] h-screen w-screen" />
				<Link href="/">home gan</Link>
			</main>
		</div>
	)
}

export default Home
